version: '3.8'

services:
  # 1. Database Service
  postgres-db:
    image: postgres:15-alpine
    container_name: my-db
    environment:
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: expense_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  # 2. Backend Service (Spring Boot)
  backend:
    build: /backend
    container_name: my-backend
    # ports:
    # - "8080:8080"      # เปิด Port 8080
    expose:
      - "8080"
    depends_on:
      - postgres-db      # รอให้ DB รันก่อน
    environment:
      # ตั้งค่าให้ Spring Boot คุยกับ Container ชื่อ 'postgres-db'
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/expense_db
      SPRING_DATASOURCE_USERNAME: user123
      SPRING_DATASOURCE_PASSWORD: password123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  frontend:
    build: /frontend
    container_name: my-frontend
    # ports:
    # - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - backend
    environment:
      # URL ของ Backend เวลาเรียกจาก Server-side (ถ้ามี)
      API_URL: http://backend:8080
  nginx:
    image: nginx:alpine
    container_name: my-nginx
    ports:
      - "80:80" # เข้าผ่าน Port 80 มาตรฐานเว็บ
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # เอา config เราใส่เข้าไป
    depends_on:
      - frontend
      - backend
volumes:
  db-data: