services:
  # Database Service
  postgres-db:
    image: postgres:17-alpine
    container_name: expense-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}    
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  # Backend Service (Spring Boot)
  backend:
    build: ./backend
    container_name: expense-backend
    expose:
      - "${BACKEND_PORT}"
    depends_on:
      - postgres-db
    environment:
      # ตั้งค่าให้ Spring Boot คุยกับ Container
      APP_DB_URL: jdbc:postgresql://postgres-db:5432/${POSTGRES_DB}
      APP_DB_USER: ${POSTGRES_USER}
      APP_DB_PASSWORD: ${POSTGRES_PASSWORD}

  frontend:
    build: ./frontend
    container_name: expense-frontend
    expose:
      - "${FRONTEND_PORT}"
    depends_on:
      - backend


  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: expense-nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # เอา config เราใส่เข้าไป
    depends_on:
      - frontend
      - backend
volumes:
  db-data: